import { useAuth } from "@/_core/hooks/useAuth";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { trpc } from "@/lib/trpc";
import { Activity, Calendar, FileText, Loader2, Play, Settings } from "lucide-react";
import { Link } from "wouter";
import { toast } from "sonner";

export default function Dashboard() {
  const { user } = useAuth();
  const utils = trpc.useUtils();
  const { data: posts, isLoading: postsLoading } = trpc.posts.list.useQuery();
  const { data: logs, isLoading: logsLoading } = trpc.publication.logs.useQuery();
  const triggerPublication = trpc.publication.trigger.useMutation({
    onMutate: () => {
      toast.info("🤖 Generating article...", {
        description: "This will take 2-5 minutes. AI models are writing in parallel.",
        duration: 5000,
      });
    },
    onSuccess: () => {
      toast.success("✅ Article generated successfully!", {
        description: "Check the Posts page to review and approve it.",
        duration: 10000,
      });
      // Auto-refresh lists
      utils.posts.list.invalidate();
      utils.publication.logs.invalidate();
    },
    onError: (error) => {
      toast.error("❌ Failed to generate article", {
        description: error.message,
        duration: 10000,
      });
    },
  });

  const stats = {
    totalPosts: posts?.length || 0,
    publishedPosts: posts?.filter(p => p.status === 'published').length || 0,
    draftPosts: posts?.filter(p => p.status === 'draft').length || 0,
    successfulPublications: logs?.filter(l => l.status === 'success').length || 0,
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 to-indigo-100">
      <div className="container py-8">
        <div className="flex justify-between items-center mb-8">
          <div>
            <h1 className="text-3xl font-bold">Dashboard</h1>
            <p className="text-muted-foreground">Welcome back, {user?.name}</p>
          </div>
          <div className="flex gap-2">
            <Button asChild variant="outline">
              <Link href="/configuration">
                <Settings className="w-4 h-4 mr-2" />
                Configuration
              </Link>
            </Button>
            <Button 
              onClick={() => triggerPublication.mutate()}
              disabled={triggerPublication.isPending}
            >
              {triggerPublication.isPending ? (
                <>
                  <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                  Generating...
                </>
              ) : (
                <>
                  <Play className="w-4 h-4 mr-2" />
                  Trigger Publication
                </>
              )}
            </Button>
          </div>
        </div>

        <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-6 mb-8">
          <Card>
            <CardHeader className="pb-3">
              <CardTitle className="text-sm font-medium text-muted-foreground">
                Total Posts
              </CardTitle>
            </CardHeader>
            <CardContent>
              <div className="text-3xl font-bold">{stats.totalPosts}</div>
            </CardContent>
          </Card>

          <Card>
            <CardHeader className="pb-3">
              <CardTitle className="text-sm font-medium text-muted-foreground">
                Published
              </CardTitle>
            </CardHeader>
            <CardContent>
              <div className="text-3xl font-bold text-green-600">{stats.publishedPosts}</div>
            </CardContent>
          </Card>

          <Card>
            <CardHeader className="pb-3">
              <CardTitle className="text-sm font-medium text-muted-foreground">
                Drafts
              </CardTitle>
            </CardHeader>
            <CardContent>
              <div className="text-3xl font-bold text-yellow-600">{stats.draftPosts}</div>
            </CardContent>
          </Card>

          <Card>
            <CardHeader className="pb-3">
              <CardTitle className="text-sm font-medium text-muted-foreground">
                Successful Publications
              </CardTitle>
            </CardHeader>
            <CardContent>
              <div className="text-3xl font-bold text-blue-600">{stats.successfulPublications}</div>
            </CardContent>
          </Card>
        </div>

        <div className="grid lg:grid-cols-2 gap-6">
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <FileText className="w-5 h-5" />
                Recent Posts
              </CardTitle>
              <CardDescription>Latest blog posts generated by AI</CardDescription>
            </CardHeader>
            <CardContent>
              {postsLoading ? (
                <div className="text-center py-8 text-muted-foreground">Loading...</div>
              ) : posts && posts.length > 0 ? (
                <div className="space-y-4">
                  {posts.slice(0, 5).filter(post => post && post.id).map(post => (
                    <div key={`post-${post.id}`} className="border-b pb-3 last:border-0">
                      <div className="flex justify-between items-start">
                        <div className="flex-1">
                          <h3 className="font-medium">{post.title}</h3>
                          <div className="flex gap-2 mt-1 text-sm text-muted-foreground">
                            <span className="capitalize">{post.aiWriter}</span>
                            <span>•</span>
                            <span>Score: {post.totalScore}/100</span>
                            <span>•</span>
                            <span className="capitalize">{post.status}</span>
                          </div>
                        </div>
                      </div>
                    </div>
                  ))}
                  <Button asChild variant="outline" className="w-full mt-4">
                    <Link href="/posts">View All Posts</Link>
                  </Button>
                </div>
              ) : (
                <div className="text-center py-8 text-muted-foreground">
                  No posts yet. Trigger a publication to get started.
                </div>
              )}
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Activity className="w-5 h-5" />
                Publication Log
              </CardTitle>
              <CardDescription>Recent publication attempts</CardDescription>
            </CardHeader>
            <CardContent>
              {logsLoading ? (
                <div className="text-center py-8 text-muted-foreground">Loading...</div>
              ) : logs && logs.length > 0 ? (
                <div className="space-y-3">
                  {logs.slice(0, 5).filter(log => log && log.id).map(log => (
                    <div key={`log-${log.id}`} className="flex items-center gap-3 border-b pb-3 last:border-0">
                      <div className={`w-2 h-2 rounded-full ${
                        log.status === 'success' ? 'bg-green-500' : 
                        log.status === 'failed' ? 'bg-red-500' : 'bg-yellow-500'
                      }`} />
                      <div className="flex-1">
                        <div className="text-sm font-medium capitalize">{log.status}</div>
                        <div className="text-xs text-muted-foreground">
                          {new Date(log.publishedAt).toLocaleString()}
                        </div>
                        {log.errorMessage && (
                          <div className="text-xs text-red-600 mt-1">{log.errorMessage}</div>
                        )}
                      </div>
                    </div>
                  ))}
                </div>
              ) : (
                <div className="text-center py-8 text-muted-foreground">
                  No publication logs yet.
                </div>
              )}
            </CardContent>
          </Card>
        </div>

        <Card className="mt-6">
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Calendar className="w-5 h-5" />
              Publication Schedule
            </CardTitle>
            <CardDescription>Automatic publication schedule</CardDescription>
          </CardHeader>
          <CardContent>
            <div className="space-y-3">
              <div className="flex items-center gap-3">
                <div className="w-12 h-12 rounded-lg bg-blue-100 flex items-center justify-center">
                  <Calendar className="w-6 h-6 text-blue-600" />
                </div>
                <div>
                  <div className="font-medium">Monday at 9:00 AM GMT+1</div>
                  <div className="text-sm text-muted-foreground">Weekly publication</div>
                </div>
              </div>
              <div className="flex items-center gap-3">
                <div className="w-12 h-12 rounded-lg bg-purple-100 flex items-center justify-center">
                  <Calendar className="w-6 h-6 text-purple-600" />
                </div>
                <div>
                  <div className="font-medium">Thursday at 9:00 AM GMT+1</div>
                  <div className="text-sm text-muted-foreground">Weekly publication</div>
                </div>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
